version: "2.4"
services:
  jupyter:
    image: jupyter/base-notebook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    command: poetry run jupyter lab --ip=0.0.0.0 --port=${JUPYTER_PORT} --allow-root
    volumes:
      - "./:/app/:cached"
    deploy:
      resources:
        # consider updating these limits
        limits:
          cpus: "4"
          memory: 8GB

  jupyter-gpu:
    image: jupyter/base-notebook
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        GPU_RUNTIME: nvidia
    shm_size: "8gb"
    ports:
      - "${JUPYTER_PORT_GPU}:${JUPYTER_PORT_GPU}"
    command: poetry run jupyter lab --ip=0.0.0.0 --port=${JUPYTER_PORT_GPU} --allow-root
    volumes:
      - "./:/app/:cached"
    deploy:
      resources:
        # consider updating these limits
        limits:
          cpus: "32"
          memory: 500GB
        reservations:
          devices:
          - driver: "nvidia"
            capabilities: [gpu]
    environment:
      CUDA_DEVICE_ORDER: PCI_BUS_ID
