# pytorch_lightning==1.8.6
seed_everything: true
trainer:
  logger: true
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: null
      monitor: val_loss
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: 1
      save_on_train_epoch_end: null
  default_root_dir: /app/data/baselines/line_item_detection/table_transformer/
  gradient_clip_val: 0.1
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: 1
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 1000
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 20
  accelerator: gpu
  strategy: null
  sync_batchnorm: false
  precision: 16
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
model:
  description: Fine-tuning for table detection (full table bbox)
  train_dataset_name: train
  val_dataset_name: val
  task: table-detection
  initial_checkpoint: facebook/detr-resnet-50
  dataset_path: /app/data/docile/
  load_ground_truth_crop_bboxes: false
  predictions_root_dir: /app/data/baselines/line_item_detection/table_transformer/predictions/
  crop_bboxes_filename: null
  lr: 3.0e-05
  lr_backbone: 3.0e-07
  weight_decay: 0.0001
  batch_size: 32
  num_workers: 16
  threshold: 0.5
ckpt_path: null
